syntax = "proto3";

package payment;

option go_package = "order-service/proto/paymentpb";

service PaymentService {
  rpc ProcessPayment (PaymentRequest) returns (PaymentResponse);
}

message PaymentRequest {
  string order_id = 1;
  int64 amount = 2;
}

message PaymentResponse {
  string status = 1;
  string transaction_id = 2;
}

message OrderRequest {
  string order_id = 1;
}

message OrderStatusUpdate {
  string order_id = 1;
  string status = 2;
}

message GetPaymentStatsRequest {}

message PaymentStats {
  int64 total_count = 1;
  int64 authorized_count = 2;
  int64 declined_count = 3;
  int64 total_amount = 4;
}

service OrderService {
  rpc SubscribeToOrderUpdates (OrderRequest) returns (stream OrderStatusUpdate);
  rpc ProcessPayment(PaymentRequest) returns (PaymentResponse);
  rpc GetPaymentStats(GetPaymentStatsRequest) returns (PaymentStats);
}
